# Project information
site_name: Git Query language
site_url: https://amrdeveloper.github.io/gql
site_description: A SQL Like query language to perform queries on .git files.
site_author: AmrDeveloper

# Repository
repo_name: Amrdeveloper/GQL
repo_url: https://github.com/amrdeveloper/GQL

# Copyright
copyright: Copyright &copy; 2023 Amr Hesham

# Configuration
theme:
  name: material
  logo: assets/gql_logo.svg
  favicon: assets/gql_logo.svg

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

  font:
    code: JetBrains Mono

  palette:
    - scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  features:
    - content.code.annotate
    - content.code.copy
    - content.action.edit

  plugins:
    - optimize
    - offline

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Page tree
nav:
  - Home: index.md
  - Setup: setup.md
  - Structure:
      - Tables: structure/tables.md
      - Types: structure/types.md
  - Statement:
      - Variables: statement/variables.md
      - Select: statement/select.md
      - Where: statement/where.md
      - Group by: statement/group_by.md
      - Having: statement/having.md
      - Order by: statement/order_by.md
      - Limit & Offset: statement/limit_and_offset.md
  - Expression:
      - Unary: expression/unary.md
      - Binary: expression/binary.md
      - Case: expression/case.md
  - Function:
      - Functions: function/functions.md
      - Aggregations: function/aggregations.md
  - Libraries: libraries.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/amrdeveloper
      name: AmrDeveloper on Github
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AmrDeveloper
      name: AmrDeveloper on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/amrdeveloper
      name: AmrDeveloper on Linkedin
    - icon: fontawesome/brands/medium
      link: https://amrdeveloper.medium.com
      name: AmrDeveloper on Medium
