# Project information
site_name: Git Query language
site_url: https://amrdeveloper.github.io/gql
site_description: A SQL Like query language to perform queries on .git files.
site_author: AmrDeveloper

# Repository
repo_name: Amrdeveloper/GQL
repo_url: https://github.com/amrdeveloper/GQL

# Copyright
copyright: Copyright &copy; 2024 Amr Hesham

# Configuration
theme:
  name: material
  logo: assets/gql_logo.svg
  favicon: assets/gql_logo.svg

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

  font:
    code: JetBrains Mono

  palette:
    - scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  features:
    # Content features
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.action.edit
    - content.tooltips

    # Navigation features
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking

    # Search features
    - search.suggest
    - search.highlight
    - search.share

  plugins:
    - optimize
    - offline
    - search

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Page tree
nav:
  - GitQL:
    - Setup: setup.md
    - Structure:
      - Tables: structure/tables.md
      - Types: structure/types.md
    - Statements:
      - "statement/index.md"
      - Variables: statement/variables.md
      - Do: statement/do.md
      - Select: statement/select.md
      - Where: statement/where.md
      - Group by: statement/group_by.md
      - Having: statement/having.md
      - Order by: statement/order_by.md
      - Limit & Offset: statement/limit_and_offset.md
    - Expression:
      - "expression/index.md"
      - Array: expression/array.md
      - Unary: expression/unary.md
      - Binary: expression/binary.md
      - Case: expression/case.md
      - Cast: expression/cast.md
      - Access Member: expression/access.md
      - Call: expression/call.md
    - STD Functions and Operators:
      - "functions/index.md"
      - Logical: functions/logical.md
      - Comparison: functions/comparison.md
      - Mathematical: functions/math.md
      - String: functions/string.md
      - Date/Time: functions/datetime.md
      - Regex: functions/regex.md
      - Array: functions/array.md
      - Range: functions/range.md
      - Other: functions/other.md
      - Aggregate Functions: functions/aggregations.md
      - Window Functions: functions/window.md
    - GitQL Functions: gitql_functions.md
  - GitQL SDK:
    - "sdk/index.md"
    - Schema: sdk/schema.md
    - Data Provider: sdk/provider.md
    - Functions: sdk/functions.md
    - Types: sdk/types.md
    - Values: sdk/values.md
    - Start the SDK: sdk/assemble.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/amrdeveloper
      name: AmrDeveloper on Github
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AmrDeveloper
      name: AmrDeveloper on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/amrdeveloper
      name: AmrDeveloper on Linkedin
    - icon: fontawesome/brands/medium
      link: https://amrdeveloper.medium.com
      name: AmrDeveloper on Medium
